version: "3.8"
services:
  api:
    build:
      context: ./api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/app # Optional for local development

  client:
    build:
      context: ./client
      args:
        NEXT_BUILD: "true"
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
    command: npm start